### ISSUE TITLE
Generating a TrackDataset fails when Wisconsin SSEC server is down

### ISSUE THREAD

**Issue by trwhitcomb** [tropycal/tropycal#100]
Instantiating a track dataset for a particular storm when the Wisconsin SSEC server is down leads to timeout errors and crashes in the code.  The call to load data is in the get_archer routine, and there is no try/except block around the https request.

Adding a try/except block to handle connection errors (i.e. timeouts) and return ARCHER data as an empty dictionary allows the code to run successfully and not crash.

**Comment by splillo** [comment]
Thanks for raising this issue! We ran into this at the same time too and have it fixed for the next version release coming soon.
