### ISSUE TITLE
Dataset Summary

### ISSUE THREAD

**Issue by virjay** [tropycal/tropycal#104]
From the Python example code provided, with the option: (basin='north_atlantic',source='hurdat',include_btk=False) - The number of storms is given as 1893 in Dataset Summary, where as if I count the number of lines with 'AL' in it (The prefix for Storm ID), I get 1894.

**Comment by tomerburg** [comment]
I haven't been able to replicate this issue on my end - it's also possible it was inadvertently fixed along the way since this issue was first opened. I'll close this issue in the meantime - feel free to re-open should this discrepancy come up again.
