### ISSUE TITLE
Release Tropycal on conda-forge

### ISSUE THREAD

**Issue by famiuer** [tropycal/tropycal#108]
**Is your feature request related to a problem? Please describe.**
Tropycal is only available via PyPI and github.

**Describe the solution you'd like**
Many people in the scientific and engineering community use Anaconda distribution of Python. This is especially important because some libraries cannot be built on Windows via pip and conda provides pre-compiled binaries of those (recent example - numpy, though they have added wheels on PyPI so its not an issue anymore).

**How to do it**
[Instructions here](https://conda-forge.org/#add_recipe) 

**Others**
Please remember to include your license in the MANIFEST file.

Thanks for your brilliant work!

**Comment by raybellwaves** [comment]
can be closed when https://github.com/conda-forge/staged-recipes/pull/15390 is merged

**Comment by raybellwaves** [comment]
for reference I used this site https://www.marcelotrevisani.com/grayskull

**Comment by famiuer** [comment]
[conda-forge/staged-recipes#15390](https://github.com/conda-forge/staged-recipes/pull/15390) is merged
