### ISSUE TITLE
Matplotlib and Cartopy Deprecations

### ISSUE THREAD

**Issue by srmullens** [tropycal/tropycal#110]
When attempting to plot gridded_stats, deprecation warnings from Cartopy are returned.
Even with these fixed, a plot doesn't appear for me, but I'll keep it to the deprecations and my suggested fixes in this issue.

Code:
```
import tropycal.tracks as tracks
hurdat = tracks.TrackDataset(basin='north_atlantic',source='hurdat',include_btk=True)
hurdat.gridded_stats('maximum wind')
```

Returns:
--> Starting to read in HURDAT2 data
--> Completed reading in HURDAT2 data (2.66 seconds)
--> Starting to read in best track data
--> Completed reading in best track data (11.7 seconds)
maximum wind
--> Getting filtered storm tracks
--> Grouping by lat/lon/storm
* .../python3.8/site-packages/cartopy/mpl/gridliner.py:324: UserWarning: The .xlabels_top attribute is deprecated. Please use .top_labels to toggle visibility instead.
  warnings.warn('The .xlabels_top attribute is deprecated. Please '
* .../python3.8/site-packages/cartopy/mpl/gridliner.py:360: UserWarning: The .ylabels_right attribute is deprecated. Please use .right_labels to toggle visibility instead.
  warnings.warn('The .ylabels_right attribute is deprecated. Please '

--> Generating plot
* .../python3.8/site-packages/cartopy/mpl/geoaxes.py:1887: MatplotlibDeprecationWarning: shading='flat' when X and Y have the same dimensions as C is deprecated since 3.3.  Either specify the corners of the quadrilaterals with X and Y, or pass shading='auto', 'nearest' or 'gouraud', or set rcParams['pcolor.shading'].  This will become an error two minor releases later.
  result = matplotlib.axes.Axes.pcolor(self, *args, **kwargs)
* .../python3.8/site-packages/cartopy/mpl/geoaxes.py:1887: MatplotlibDeprecationWarning: Passing parameters norm and vmin/vmax simultaneously is deprecated since 3.3 and will become an error two minor releases later. Please pass vmin/vmax directly to the norm when creating it.
  result = matplotlib.axes.Axes.pcolor(self, *args, **kwargs)
* .../python3.8/site-packages/tropycal/tracks/plot.py:1596: MatplotlibDeprecationWarning: 
The inverse_transformed function was deprecated in Matplotlib 3.3 and will be removed two minor releases later. Use transformed(transform.inverted()) instead.
  bb = l.legendPatch.get_bbox().inverse_transformed(self.fig.transFigure)

For the first two errors, it seems the following line can be changed:
tropycal/plot/plot.py:232:
```
gl.xlabels_top = False
gl.ylabels_right = False
```

change this to:
```
gl.top_labels = False
gl.right_labels = False
```

For the third and fourth errors, it seems the following line can be changed:
tropycal/tracks/plot.py:1563:
`cbmap = self.ax.pcolor(xcoord,ycoord,zcoord,cmap=cmap,vmin=vmin,vmax=vmax,norm=norm,transform=ccrs.PlateCarree())`

change this to:
`cbmap = self.ax.pcolor(xcoord,ycoord,zcoord,cmap=cmap,norm=norm,shading='auto',transform=ccrs.PlateCarree())`

For the fifth error, it seems the following line can be changed:
tropycal/tracks/plot.py:1596:
`bb = l.legendPatch.get_bbox().transformed(self.fig.transFigure.inverted())`

change this to:
`bb = l.legendPatch.get_bbox().transformed(self.fig.transFigure.inverted())`

My relevant package versions are:
conda                     4.8.2
cartopy                   0.19.0.post1
matplotlib                3.4.1
python                    3.8.8
tropycal                  0.2.4

**Comment by tomerburg** [comment]
As this issue is a duplicate issue of a more recent one opened (#131), I will be closing this issue and continuing the discussion from there.
