### ISSUE TITLE
Feature request: tropycal.tracks.Dataset.to_dataframe()

### ISSUE THREAD

**Issue by raybellwaves** [tropycal/tropycal#115]
There is currently a to_dataframe method associated with tropycal.tracks.Storm and tropycal.tracks.Season.

This may require expanding the current columns returned in the above method so that when a Datasets data are appended they remain unique e.g. basin and and year

**Comment by tomerburg** [comment]
As this issue has already been addressed in a merged PR that implemented this feature, I will be closing this issue.
