### ISSUE TITLE
plot_gefs_ensembles error when choosing 00z

### ISSUE THREAD

**Issue by scaparotta** [tropycal/tropycal#123]
There appears to be a bug when attempting to plot GEFS ensembles using the 00z run. I tried for both 10-11 Aug 2021 with Fred and got the same error. Other hours (6/12/18) plot fine.

```
import matplotlib.pyplot as plt
from tropycal import tracks, tornado, recon
import numpy as np
import pandas as pd
from datetime import datetime as dt,timedelta

basin = tracks.TrackDataset('north_atlantic', source='hurdat', include_btk=True)

storm = basin.get_storm(('Fred',2021))
print(storm)

storm.to_dataframe()
print(storm.to_xarray())

storm.plot()
storm.plot_nhc_forecast(dt(2021,8,11,3))
storm.plot_gefs_ensembles(forecast = dt(2021,8,11,0), fhr = [168])
```

Error returned:
Traceback (most recent call last):
  File ".\gefs_plot.py", line 17, in <module>
    storm.plot_gefs_ensembles(forecast = dt(2021,8,11,0), fhr = [168])
  File "C:\ProgramData\Anaconda3\lib\site-packages\tropycal\tracks\storm.py", line 967, in plot_gefs_ensembles
    plot_ax = self.plot_obj.plot_ensembles(forecast,self.dict,fhr,prop_members,prop_mean,prop_gfs,prop_ellipse,prop_density,nens,domain,ds,ax=ax,return_ax=return_ax,map_prop=map_prop,save_path=save_path)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tropycal\tracks\plot.py", line 1189, in plot_ensembles
    use_lats = ds['gfs']['lat'][:idx+1]
TypeError: only integer scalar arrays can be converted to a scalar index

**Comment by tomerburg** [comment]
The original poster and I have already separately discussed this issue, but the entire ``plot_gefs_ensembles()`` function needs a substantial overhaul as it is full of many bugs and incomplete functionality. This is a task I'm assigning for the next Tropycal release - I'll check back on this issue once a fix has been made.

**Comment by tomerburg** [comment]
It's been a while since I last worked on this, but the ``plot_gefs_ensembles()`` function has just been overhauled and thoroughly debugged, and was able to run your sample code successfully! These changes will be part of the upcoming Tropycal v0.5 release, so I'll close this issue once the release is out.

![image](https://user-images.githubusercontent.com/23174572/177633746-4cadbdb7-91f8-4978-b92c-e3145f432247.png)

**Comment by scaparotta** [comment]
Great news...thanks, Tomer! Looking forward to trying out v0.5

Steve
