### ISSUE TITLE
geopy requirement

### ISSUE THREAD

**Issue by raybellwaves** [tropycal/tropycal#132]
In the README it says geopy is required (https://github.com/tropycal/tropycal/blob/master/README.md#dependencies)

but I don't see it in the requirements of the package build https://github.com/tropycal/tropycal/blob/master/setup.cfg#L28

I see it may be requires for the docs build https://github.com/tropycal/tropycal/blob/master/docs/requirements.txt
but that file may be old?

I can't see where geopy is used in the codebase as well

**Comment by tomerburg** [comment]
Yes, this would be correct - there was an earlier PR to remove geopy as a dependency as it is no longer used, but it appears geopy mentions weren't completely removed from the code. I opened up a new bug fix branch and will remove all remaining geopy mentions and requirements.

I'm not sure if doing so will automatically remove geopy as a dependence on conda-forge or if that will require a separate action - in the meantime I'll keep this issue open.

**Comment by tomerburg** [comment]
All geopy references were removed with the last Tropycal update; as such I’ll be closing this issue. Thanks for notifying us again!
