### ISSUE TITLE
generic_utils / get_basin() and storm_id length

### ISSUE THREAD

**Issue by srmullens** [tropycal/tropycal#133]
The get_basin() function uses the storm_id to determine if a storm is in the north_atlantic or north_pacific basin. But to determine the basin, it demands the storm_id length be 9 characters. 
```
if len(storm_id) != 9:
```
But I believe storm IDs are 8 characters (AL012021).
If I'm right, tropycal/utils/generic_utils.py line 321 should be:
```
if len(storm_id) != 8:
```

**Comment by tomerburg** [comment]
That would be correct - great catch! Unfortunately I missed this for v0.3.1 (other bugs were of higher priority short-term), but I created a new bug fix branch and will fix this bug. Once this has been resolved and merged with a PR I'll close this issue.

**Comment by tomerburg** [comment]
This issue was fixed with the last Tropycal release; as such I’m closing this issue. Thanks again for notifying us!
