### ISSUE TITLE
Unable to plot rainfall data

### ISSUE THREAD

**Issue by jwu1982** [tropycal/tropycal#142]
Good morning, 

I am trying to plot a rainfall map for Hurricane Harvey in 2017. However, I have been unable to generate a map. Namely, I am unsure how to type in the code to generate the rainfall map itself. I have tried "storm.plot_rain" and some other commands to no avail. Please refer to my attached link for additional information and a screenshot of the text I have entered.

Please note that I am new to Tropycal and programming in general. I would appreciate any input. Thank you!

Thank you in advance!

https://docs.google.com/drawings/d/1pZ64sEiSevDPf_rrh9XpfUWrHp1lBJvE7OYi4sp8S_c/edit?usp=sharing

Sincerely, 

Andrew Peter Tillerman

**Comment by tomerburg** [comment]
There's a few extra steps you need to follow to retrieve the storm rainfall - by default `Storm` objects don't contain TC rainfall. To do so you'll need to retrieve a dataset of all TC rainfall:

`
from tropycal import rain
rain_obj = rain.RainDataset()`

Once you have this stored, you can then plot the rainfall for your Storm object, if the WPC dataset contains rain totals for that storm, directly from the rain object:

`rain_obj.plot_rain(storm,....)`

We have an example of this in the link below:
https://github.com/tropycal/sample-scripts/blob/main/tropycal_v0.3_sample.ipynb

In future versions we may add rain data directly to storm objects, but currently this is not a capability. I'll be closing this issue unless you encounter any more bugs, in which case you can open a new issue or re-open this one, or if you have more questions feel free to open a discussion topic on it.
