### ISSUE TITLE
Become a SSLCertVerificationError while using tropycal

### ISSUE THREAD

**Issue by finnjonasrolf** [tropycal/tropycal#143]
Dear Developer and Community, 

i try to use tropycal with conda and first i want to start by using your example scripts from your website. 

I try to open "tracks.storm.py" with the newest version of conda and tropycal, but i become a SSLCertVerificationError : certificate verify failed: certificate has expired (_ssl.c:1129). Any Ideas to solve this problem? 
I got the same problem on two different devices.

Thanks for your help :)

**Comment by tomerburg** [comment]
Thank you for opening an issue. Can you provide a more specific example of code that triggers this error? We are aware of this occurring for storms read in from Realtime objects with the source set to JTWC, but not of other cases unless it may be related to your internet connection.

**Comment by finnjonasrolf** [comment]
The Issue triggers in your example "tracks.storm.py" in this line :
`hurdat_atl = tracks.TrackDataset(basin='north_atlantic',source='hurdat',include_btk=False)`

I installed a new certificate and fixed the problem. I think it wasn't a problem with tropycal, but other Connections worked fine. Maybe old certificates generate this error with encrypted connections. 
Thanks for your help ^^
