### ISSUE TITLE
Unable to import tracks

### ISSUE THREAD

**Issue by winash12** [tropycal/tropycal#148]
`from tropycal import tracks`

With the latest version of tropycal I get this error - 

`Traceback (most recent call last):
  File "gridded.py", line 1, in <module>
    from tropycal import tracks
ImportError: cannot import name 'tracks' from 'tropycal' (/usr/local/lib/python3.8/dist-packages/tropycal-0.3.3-py3.8.egg/tropycal/__init__.py)`

**Comment by tomerburg** [comment]
At a quick glance I would suspect this may be something with your environment and outside of our control, but I can check to make sure. Did this work with previous Tropycal versions but stop working now, or did importing Tropycal never work on your end? How did you install Tropycal (conda, pip, directly from source)?

**Comment by winash12** [comment]
Tropycal worked fine before. Made several plots. I installed directly from source.

**Comment by winash12** [comment]
Any update on this one ? I installed the latest version 0.4 and I still get the same error. I just think something is wrong with the src/tropycal/tropycal appearing twice.

**Comment by winash12** [comment]
https://stackoverflow.com/questions/43728431/relative-imports-modulenotfounderror-no-module-named-x Is it this issue ?

**Comment by winash12** [comment]
This problem has been fixed in version 0.6
