### ISSUE TITLE
Unable to read South Indian tracks

### ISSUE THREAD

**Issue by More-Grace** [tropycal/tropycal#168]
Hie,
I just run the line below. I am doing a research on the south Indian Cyclones.

`ds_ibtracs = tracks.TrackDataset(basin='south_indian',source='ibtracs',ibtracs_mode='jtwc_neumann')`
  
 I am getting the following error message.

``KeyError                                  Traceback (most recent call `last)
<ipython-input-7-216034cd0726> in <module>
----> 1 ds_ibtracs = tracks.TrackDataset(basin='south_indian',source='ibtracs',ibtracs_mode='jtwc_neumann')

C:\ProgramData\Anaconda3\lib\site-packages\tropycal\tracks\dataset.py in __init__(self, basin, source, include_btk, interpolate_data, **kwargs)
    204             self.__read_hurdat()
    205         elif source == 'ibtracs':
--> 206             self.__read_ibtracs()
    207         else:
    208             raise RuntimeError("Accepted values for 'source' are 'hurdat' or 'ibtracs'")

C:\ProgramData\Anaconda3\lib\site-packages\tropycal\tracks\dataset.py in __read_ibtracs(self)
   1024 
   1025                 #plug dict entry
-> 1026                 old_entry = self.data[jtwc_id]
   1027                 self.data[jtwc_id] = neumann[key]
   1028 

KeyError: `'SH011961``

Thank you.

**Comment by tomerburg** [comment]
Thanks for reporting this issue! This appears to have been an inadvertent result from a bug fix in reading Australian basin cyclones, specifically with filtering out storms from the Neumann reanalysis. I just added a bug fix for this which will be implemented in the upcoming v0.5.2 release.

**Comment by More-Grace** [comment]
Duly noted. Thank you very much.
