### ISSUE TITLE
Trend Analysis using the Tropical Package 

### ISSUE THREAD

**Issue by More-Grace** [tropycal/tropycal#172]
Is it possible to perform trend analysis in the tropycal package for the South Indian dataset per year, season, and possibly months? 

Thank you.

**Comment by winash12** [comment]
@More-Grace Could you clarify your question ? What do you mean by trend analysis ? Given the dataset of all cyclones for a season you have some parameter on which you want to remove the linear trend ?

**Comment by More-Grace** [comment]
> @More-Grace Could you clarify your question ? What do you mean by trend analysis ? Given the dataset of all cyclones for a season you have some parameter on which you want to remove the linear trend ? If you have a numpy array coming out of troPYcal you can convert that into a pandas dataframe and start to do trend analysis.

**Comment by More-Grace** [comment]
@winash12  Thank you. Yes, I wanted to get the linear trend of the cyclones per month and season.
