### ISSUE TITLE
decode_hdob(content) throwing value error while conducting mission search operation

### ISSUE THREAD

**Issue by kylejgillett** [tropycal/tropycal#173]
Hello,

I am attempting to run... 

`from tropycal import recon
realtime_obj = recon.RealtimeRecon()`

...but on occasion, I will receive a ValueError during the decode_hdobs function within the realtime_obj = recon.RealtimeRecon() operation. I will attach the output after running this code below. Any thoughts? At the end of the day, my main goal is to retrieve recent dropsonde data. 

Thanks

OUTPUT:
`--> Searching for active missions

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [9], in <cell line: 2>()
      1 from tropycal import recon
----> 2 realtime_obj = recon.RealtimeRecon()

File ~\miniconda3\lib\site-packages\tropycal\recon\realtime.py:122, in RealtimeRecon.__init__(self, hours)
    115         self.missions[mission_id] = {'hdobs':decode_hdob(content),
    116                                 'vdms':[],
    117                                 'dropsondes':[],
    118                                 'aircraft':mission_id.split("-")[0],
    119                                 'storm_name':mission_id.split("-")[2]
    120                                }
    121     else:
--> 122         self.missions[mission_id]['hdobs'] = pd.concat([self.missions[mission_id]['hdobs'],decode_hdob(content)])
    124 #Retrieve VDMs
    125 for file in files['vdms']:
    126 
    127     #Retrieve content

File ~\miniconda3\lib\site-packages\tropycal\recon\tools.py:802, in decode_hdob(content, mission_row)
    800 data['dwpt'] = [np.nan if '/' in i[7] else round(float(i[7])*0.1,1) for i in items[3:]]
    801 data['wdir'] = [np.nan if '/' in i[8][:3] else round(float(i[8][:3]),0) for i in items[3:]]
--> 802 data['wspd'] = [np.nan if '/' in i[8][3:] else round(float(i[8][3:]),0) for i in items[3:]]
    803 data['pkwnd'] = [np.nan if '/' in i[9] else round(float(i[9]),0) for i in items[3:]]
    804 data['sfmr'] = [np.nan if '/' in i[10] else round(float(i[10]),0) for i in items[3:]]

File ~\miniconda3\lib\site-packages\tropycal\recon\tools.py:802, in <listcomp>(.0)
    800 data['dwpt'] = [np.nan if '/' in i[7] else round(float(i[7])*0.1,1) for i in items[3:]]
    801 data['wdir'] = [np.nan if '/' in i[8][:3] else round(float(i[8][:3]),0) for i in items[3:]]
--> 802 data['wspd'] = [np.nan if '/' in i[8][3:] else round(float(i[8][3:]),0) for i in items[3:]]
    803 data['pkwnd'] = [np.nan if '/' in i[9] else round(float(i[9]),0) for i in items[3:]]
    804 data['sfmr'] = [np.nan if '/' in i[10] else round(float(i[10]),0) for i in items[3:]]

ValueError: could not convert string to float: ''

`

**Comment by tomerburg** [comment]
Thanks for opening the issue! There was indeed a bug resulting from an improperly formatted HDOBS file from NHC's server - I added a quick bug fix that should avert this problem. I'll close this issue with the next tropycal release.

**Comment by kylejgillett** [comment]
Thanks, man, appreciate it!
