### ISSUE TITLE
Read 0 Files

### ISSUE THREAD

**Issue by lpulmano** [tropycal/tropycal#180]
When retrieving VDM, dropsonde, and HDOB from NATL 2022, it always outputs "Read 0 files"
![image](https://github.com/tropycal/tropycal/assets/95270230/0bd53c2a-cafd-477f-b88f-8f1117773008)
![image](https://github.com/tropycal/tropycal/assets/95270230/790437d7-a575-4892-b7d6-8c927925074f)

This prevents storm.recon, plot_summary(), plot_maps(), and plot_hovmuller() from working

**Comment by tomerburg** [comment]
Thank you for opening this issue! The problem originates from a potential tropical cyclone AL042022 that did not develop into a tropical cyclone, and thus was removed from HURDATv2. This affects how the operational ID is derived for each storm, as the operational ID can differ from its ID listed in HURDATv2. Earlier versions of Tropycal hard-coded a fix for these cases.

The upcoming version of Tropycal, available in the ``develop`` branch, has a fix for this by attempting to automatically identify potential tropical cyclone entries in HURDATv2. Until this update is released, you can try using the develop branch to avert this issue. Once the new version is released soon I will close this issue.

**Comment by tomerburg** [comment]
This bug was resolved with the release of v1.0, so I'm closing this issue. Thanks again for reporting the bug and please let us know if you encounter any other problems!
