### ISSUE TITLE
Possible Tropycal Update for latest Numpy release?

### ISSUE THREAD

**Issue by kylejgillett** [tropycal/tropycal#181]
Hey!

Recent changes in the latest releases of Numpy have caused some issues within (at least) the tropycal.tracks() functions. Numpy depreciated the use of np.int, np.float etc. It is now just int, float, and so forth. It's been annoying haha in all of my own scripts haha. 

Any chance of a possible fix to this at some point in the future? 

Thanks

Kyle

**Comment by tomerburg** [comment]
Thanks for opening this issue! Yes, there is already a fix for this bug implemented in the `develop` branch, but that version of Tropycal hasn't been made an official release yet. In the meantime, you can use this fix by installing Tropycal from source and using the `develop` branch. Once the next Tropycal version is released I'll close this issue.

**Comment by tomerburg** [comment]
Now that this issue was resolved with the release of v1.0, I'm closing this issue. Thanks again for reporting and please let us know if you encounter any other bugs!
