### ISSUE TITLE
link to docs in top right of github

### ISSUE THREAD

**Issue by raybellwaves** [tropycal/tropycal#186]
![Screen Shot 2023-07-18 at 11 51 53 AM](https://github.com/tropycal/tropycal/assets/17162724/9bb842c8-15b5-4334-86fc-71570657c7ea)

In the gitlab settings there should be an options to link to https://tropycal.github.io/tropycal/ as the docs

**Comment by tomerburg** [comment]
Thanks for the heads up - I just added the link to the page! If this works on your end I'll close this issue.

**Comment by raybellwaves** [comment]
thanks
