### ISSUE TITLE
Tropycal can't complete reading tornado track data

### ISSUE THREAD

**Issue by gameskip** [tropycal/tropycal#188]
Edit: see comment

So I discovered tropycal today, and found it interesting to explore, for the most part everything works (see comment for more), but I've noticed that I can't do tornado analyses, since when trying to read in tornado track data it outputs an error:

`TypeError: read_csv() got an unexpected keyword argument 'error_bad_lines'`

This error is mentioned in the tropycal home page, however in that example the tornado track data read completes, the opposite happens in my case: the error appears, but the tornado track data isn't read in and I can't use tornado track data.

**Comment by gameskip** [comment]
Note: I've resolved the image problem by adding a `save_path` argument to `storm.plot()`, however the tornado issue still exists.

**Comment by tomerburg** [comment]
Thank you for the feedback! I'll address your comments one by one:

1. I'm assuming you are using a Pandas version of 2.0.0 or newer? The "error_bad_lines" argument appears to have been removed as of that version. As it was originally deprecated with Pandas version 1.3, I updated the Tropycal develop branch requirements for the minimum Pandas version from 0.23.0 to 1.3, which will be incorporated into the main codebase with the next Tropycal release (v1.1).

2. You are correct in that the "save_path" argument is inconsistent across functions. I'll work on a bug fix for that and also incorporate it into the next Tropycal release, and will close this issue when both of these have been incorporated into the main codebase.

**Comment by gameskip** [comment]
I am indeed using a Pandas version newer than 2.0.0 (2.0.3 specifically), if there is a newer version I could maybe try to update it, but I am not aware of a newer version.

But I am happy to know that the save_path issue is in the process of getting fixed! Thanks!
