### ISSUE TITLE
Realtime docs unclear on accessing pre-invest systems

### ISSUE THREAD

**Issue by stucka** [tropycal/tropycal#194]
The code is great and the docs are generally pretty solid, but Realtime is pulling data for potential systems, and mapping them, without giving me a away to find anything about them, unless I'm doing something horribly wrong.

Realtime at the moment shows me three active Atlantic storms, which is correct; it shows me one Atlantic invest, which is correct.

It's charting the remains of TS Emily with a 20% chance of formation in seven days. The docs walk me throw charting the potential system, but it's not listed if I call the object directly. It won't get listed under active storms (OK, fair), there's no inactive storm listing. Without an identifier I can't even textually get at the 20%, which is stored somewhere, unless I map it and read the map. But ... that data is ... somewhere.

**Comment by tomerburg** [comment]
Do you have any code to show how you are attempting to retrieve the formation probability for Emily? The best I can do is provide the code I use to retrieve this information.

You should be able to retrieve Emily from its storm ID (AL072023) as follows. Please let me know if this doesn't work or if you experience issues with this.

```python
from tropycal import realtime

realtime_obj = realtime.Realtime()
storm = realtime_obj.get_storm('AL072023')

print(storm.attrs)
```

The following should be outputted:

```
{'id': 'AL072023',
 'operational_id': 'AL072023',
 'name': 'EMILY',
 'year': 2023,
 'season': 2023,
 'basin': 'north_atlantic',
 'source_info': 'NHC Hurricane Database',
 'invest': True,
 'source_method': "NHC's Automated Tropical Cyclone Forecasting System (ATCF)",
 'source_url': 'https://ftp.nhc.noaa.gov/atcf/btk/',
 'source': 'hurdat',
 'jtwc_source': 'N/A',
 'ace': 0.6875,
 'prob_2day': '20%',
 'prob_7day': '20%',
 'risk_2day': 'Low',
 'risk_7day': 'Low',
 'realtime': True}
```

**Comment by stucka** [comment]
Thank you for looking! I'm still seeing the problem with systems that haven't yet been designated as Invests. Right now:
```
from tropycal import realtime
obj = realtime.Realtime()
obj
<tropycal.realtime.Realtime>
Dataset Summary:
    Numbers of active storms: 5
    Time Updated: 1050 UTC 26 August 2023

Active Storms:
    AL082023

Active Invests:
    AL922023
    AL932023
    EP912023
    EP922023
```
And that's accurate, in that it's showing me one active Atlantic storm; two Eastern Pacific invests; and two Atlantic invests. That's three things in the Atlantic.

But if I run
`obj.plot_summary(domain={'w':-120,'e':-10,'s':4,'n':60})`

I see in the Atlantic al93 in the Gulf; al08 (Franklin) churning toward Bermuda; and al92 also heading north with a 40% chance of formation.

But on the chart I get the fourth thing, not yet designated an invest; it gets mapped coming off the coast of Africa with a 20% chance of formation, but tropycal gives me no way I've been able to find to get at anything about the 20% system, including whether it is 20%.

![samplerun](https://github.com/tropycal/tropycal/assets/533487/69f2063d-f015-4c04-b4e2-5c1b28599ea6)

**Comment by stucka** [comment]
(I recognize after posting that comment that people some would dispute al93 as "in the Gulf" vs. Caribbean Sea. I'm trying. =)  )

**Comment by tomerburg** [comment]
No worries about 93L's placement! I see what you mean now; the 20% area in the eastern Atlantic is indeed not currently designated as an invest. As it's not currently an invest, NHC does not produce best track files for it or any of the other datasets (e.g., model tracks) that would accompany invests. Realtime objects only contain information about storms that have a Best Track file associated with them. The only way to obtain information about these other areas is via TWO shapefiles, which you can fetch the latest one as follows:

```python
from tropycal import utils

two = utils.get_two_current()
```

You can then access the data it contains and attributes as follows:

```python
if two['areas'] is not None:
    for record, geom in zip(two['areas'].records(), two['areas'].geometries()):
        area_attrs = record.attributes
```

**Comment by stucka** [comment]
Thank you. That is beautiful, and gives me lots of things to kick around. I appreciate it so very much.
