### ISSUE TITLE
AttributeError using TrackPlot

### ISSUE THREAD

**Issue by alexbakey** [tropycal/tropycal#207]
I get the following error when I run `tracks.TrackDataset.gridded_stats()`:

`AttributeError: 'TrackPlot' object has no attribute 'proj'`

It is the use of the `cartopy_proj` argument that throws this error. My code is below:

```
import tropycal.tracks as tracks
import cartopy.crs as ccrs
basin = tracks.TrackDataset(basin='all',
                            source='ibtracs',
                            catarina=True)
basin.gridded_stats(request='maximum wind',
                    year_range=(1950,2023),
                    cartopy_proj=ccrs.Robinson(central_longitude=0))
```

Thanks.

**Comment by tomerburg** [comment]
Thanks for the report! I fixed this bug for the upcoming release and I'll close this issue once it's been released.

**Comment by alexanderjbaker** [comment]
Thanks!
