### ISSUE TITLE
KeyError: 'WP371996'

### ISSUE THREAD

**Issue by windcirculation** [tropycal/tropycal#209]
Hi @tomerburg, it seems Ibtracs data has been updated. I am trying to get the NIO basin, and it throws the error as shown below.
```python
basin = tracks.TrackDataset(basin='north_indian',source='ibtracs', include_btk=False)
```
```python
KeyError: 'WP371996'

```

**Comment by tomerburg** [comment]
Thanks for reporting this bug! I just fixed this issue for the upcoming release and will close this issue once it's been released.
