### ISSUE TITLE
modules don't get installed

### ISSUE THREAD

**Issue by Schamschula** [tropycal/tropycal#60]
When following the installation instructions, only `tropycal/__init__.py` gets installed, while all the  packages, i.e. plot, recon, tornado, tracks aren't installed.

Here is a patch:

```
--- setup.py.orig	2019-10-25 16:36:12.000000000 -0500
+++ setup.py	2019-10-25 19:41:26.000000000 -0500
@@ -1,6 +1,10 @@
 from setuptools import setup
 
 setup(name='tropycal',
-      packages=['tropycal'],
+      packages=['tropycal',
+                'tropycal.plot',
+                'tropycal.recon',
+                'tropycal.tornado',
+                'tropycal.tracks'],
       package_dir = { '' : 'src' },
 )
```

**Comment by zastari** [comment]
What steps are you using to install? `pip install tropycal` works out of the box for me:
```
>>> import tropycal
>>> import pkgutil
>>> [module for _, module, _ in list(pkgutil.iter_modules(tropycal.__path__))]
['plot', 'recon', 'tornado', 'tracks']
```

submodules should be available recursively as long as they all have an `__init__.py`

**Comment by Schamschula** [comment]
As I'm putting together a Portfile for MacPorts, behind the scenes, the build system is using 

`python setup.py install`.

**Comment by Schamschula** [comment]
P.S.: I got the same results by manually running `python setup.py install`
