### ISSUE TITLE
The colorbar doesn't show in the Gridded Analyses

### ISSUE THREAD

**Issue by Apolloay** [tropycal/tropycal#82]
When I try to run the [Example Code](https://tropycal.github.io/tropycal/examples/tracks.TrackDataset.html) as follow, the colorbar didn't come.

hurdat_atl = tracks.TrackDataset(basin='north_atlantic',source='hurdat',include_btk=False)
hurdat_atl.gridded_stats(request="maximum wind",return_ax=True)

I don't know what went wrong. Thank you for your excellent work.

**Comment by tomerburg** [comment]
There was a bug with the colorbar display for plots using the default sustained wind category colormap. This should be fixed with v0.2.1 that was just released yesterday.
