### ISSUE TITLE
tracks "australia" not implemented

### ISSUE THREAD

**Issue by kgoebber** [tropycal/tropycal#85]
From the documentation it appears that a basin option of "australia" could be used for getting tracks, however, in the dataset.py file the option isn't a part of the __read_ibtracs() function. It appears that it is not an option of a "basin" ob the IBTrACS website either. It appears that IBTrACS splits the southern hemisphere into souther Indian and southern Pacific. Would be nice to be able to get an "Australian" region or subset by a lat/lon box.

**Comment by tomerburg** [comment]
Hi Kevin! This is correct; this is a limitation with ibtracs, as there's no specific "Australia" basin. Currently you can only retrieve this when using the entire ibtracs dataset. A lot of our focus so far has been on HURDATv2 data, although we are working on improving ibtracs usability for our next release, and will add the ability to generate an Australian region and furthermore user-defined regions based on lat/lon bounds based on your feedback.

**Comment by tomerburg** [comment]
It took us a while to get there, but the latest round of bug fixes I'm working on includes the ability to retrieve an "Australia" basin, by retrieving the global IBTrACS dataset and subsetting to only include storms in the Australia region basin. This will be made available on the upcoming v0.5.1 update and also addresses a new issue (#164); as such I'm closing this issue.
