### ISSUE TITLE
How to retrive North Indian Ocean Cyclone data?

### ISSUE THREAD

**Issue by wxguy** [tropycal/tropycal#90]
Nice program for operational meteorologist. 

I would like to retrieve a latest cyclone "AMPHAN" data which developed over north Indian Ocean (Bay of Bengal) in May 2020. The actual data set I cold find is located at http://hurricanes.ral.ucar.edu/repository/data/bdecks_open/bio012020.dat. Therefore, I started of with a simple three line script to check if the application able  to retrieve from the url. Here is the sample lines of codes:

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import tropycal.tracks as tracks
hurdat_atl = tracks.TrackDataset(source='ibtracs', include_btk=False)
storm = hurdat_atl.get_storm(('AMPHAN', 2020))
print(storm)
```

However, I could not get the data downloaded by the program. It just got stuck at 

```
λ python track.py
--> Starting to read in current storm data
--> Completed reading in current storm data (31.9 seconds)
--> Starting to read in ibtracs data
Traceback (most recent call last):
  File "track.py", line 10, in <module>
    hurdat_atl = tracks.TrackDataset(source='ibtracs', include_btk=False)
  File "C:\Users\Sundar\AppData\Local\Programs\Python\Python38\lib\site-packages\tropycal\tracks\dataset.py", line 156, in __init__
    self.__read_ibtracs()
  File "C:\Users\Sundar\AppData\Local\Programs\Python\Python38\lib\site-packages\tropycal\tracks\dataset.py", line 580, in __read_ibtracs
    content = f.read()
  File "C:\Users\Sundar\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 467, in read
    s = self._safe_read(self.length)
  File "C:\Users\Sundar\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 610, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(13669120 bytes read, 39406525 more expected)
```

Is there a way to supply a text file with track info so that we are not dependent on internet to analyse the data? or is there an issue with my sample code provided above?

**Comment by tomerburg** [comment]
Thank you for the comments! Tropycal is not designed to store tropical cyclone data, but rather provide tools to ease the access to the existing online data, so there is nothing we can do about this issue unfortunately.
